DROP TABLE RESERVAS;
DROP TABLE PRESTAMOS;
DROP TABLE LIBROS;
DROP TABLE ALUMNOS;
DROP TABLE PROFESORES;
DROP TABLE DEPARTAMENTOS;
DROP TABLE MATRICULAS;

CREATE TABLE MATRICULAS(
ALUMNO    VARCHAR(7),
ESTUDIOS  VARCHAR(80) NOT NULL,
GRUPO     VARCHAR(10),
PRIMARY KEY(ALUMNO,GRUPO)
);

CREATE TABLE DEPARTAMENTOS(
COD_DPTO  VARCHAR(2)   PRIMARY KEY,
NOMBRE    VARCHAR(50)  NOT NULL,
CENTRO    ENUM('CIFP1','Albaladejito','Pedro Mercedes'),
DNI_JFK   VARCHAR(10),
PASSWORD  VARCHAR(100)
);

CREATE TABLE PROFESORES(
APELLIDOS  VARCHAR(50),
NOMBRE     VARCHAR(30)  NOT NULL,
DNI        VARCHAR(10)  PRIMARY KEY,
COD_DPTO   VARCHAR(2)   REFERENCES DEPARTAMENTOS(COD_DPTO)
);

CREATE TABLE ALUMNOS(
ALUMNO     VARCHAR(7)   REFERENCES MATRICULAS(ALUMNO),
APELLIDOS  VARCHAR(50),
NOMBRE     VARCHAR(30)  NOT NULL,
DNI        VARCHAR(10)  PRIMARY KEY,
NIE        VARCHAR(8)   NOT NULL
);

CREATE TABLE LIBROS(
COD_LIBRO     VARCHAR(16)   PRIMARY KEY,
COD_DEPART    VARCHAR(2)    REFERENCES DEPARTAMENTOS(COD_DPTO),
TITULO        VARCHAR(100)  NOT NULL,
EDITORIAL     VARCHAR(25),
ANIO_EDIC     VARCHAR(4),
AUTORES       VARCHAR(100),
MATERIA       VARCHAR(30),
SOPORTE_MULT  ENUM('Si','No') DEFAULT 'No',
USUARIO       ENUM('Alumno','Profesor','Consulta'),
ESTADO_FIS    ENUM('Bueno','Malo') DEFAULT 'Bueno'
);

CREATE TABLE PRESTAMOS(
NUM_PREST    INT             NOT NULL AUTO_INCREMENT,
COD_LIBRO    VARCHAR(16)     REFERENCES LIBROS(COD_LIBRO),
DNI          VARCHAR(10),
FECHA_RECOG  DATE            NOT NULL,
FECHA_DEVOL  DATE            NOT NULL,
DEVUELTO     ENUM('Si','No') DEFAULT 'No',
PRIMARY KEY(NUM_PREST)
);

CREATE TABLE RESERVAS(
COD_LIBRO  VARCHAR(16)  PRIMARY KEY REFERENCES LIBROS(COD_LIBRO),
DNI        VARCHAR(10),
FECHA_FIN  DATE         NOT NULL
);

---------------------------------------------------------------------------------

/* CREATE TABLE CLIENTES_H(
DNI         VARCHAR2(9)   CONSTRAINT C_DNI PRIMARY KEY,
NOMBRE      VARCHAR2(50)  CONSTRAINT C_NOMBRE CHECK(NOMBRE LIKE '% % %'),
TELEFONO    VARCHAR2(9)   CONSTRAINT C_TELEF CHECK(TELEFONO LIKE '_________')
);
CREATE TABLE QUEJAS_H(
NUM_QUEJA   VARCHAR2(4)     CONSTRAINT Q_NUM_QUEJA  CHECK(NUM_QUEJA LIKE '____'),
DNI         VARCHAR2(9)     CONSTRAINT Q_DNI REFERENCES CLIENTES_H,
MOTIVO      VARCHAR2(100)   DEFAULT 'No especificado' CONSTRAINT Q_MOTIVO 
                            CHECK(MOTIVO LIKE '%_%' OR MOTIVO IS NULL),
FECHA_Q     DATE,
PRIMARY KEY(NUM_QUEJA,DNI)
);
CREATE TABLE PARTE_AVERIA_H(
NUM_PARTE       VARCHAR2(4)   CONSTRAINT P_NUM_PARTE CHECK(NUM_PARTE LIKE '____'),
NUM_HABITACION  VARCHAR2(2)   CONSTRAINT P_NUM_HAB REFERENCES HABITACIONES_H,
DESPERFECTO     VARCHAR2(50)  DEFAULT 'No especificado' CONSTRAINT P_DESP 
                              CHECK(DESPERFECTO LIKE '%_%' OR DESPERFECTO IS NULL),
FECHA_P         DATE,
IMPORTE         NUMBER(6,2)   CONSTRAINT P_IMPORTE CHECK(IMPORTE>0),
PRIMARY KEY (NUM_PARTE,NUM_HABITACION),
CONSTRAINT P_CHECK CHECK(NUM_HABITACION LIKE '1%' AND NUM_PARTE LIKE '1%' OR
      NUM_HABITACION LIKE '2%' AND NUM_PARTE LIKE '2%' OR
      NUM_HABITACION LIKE '3%' AND NUM_PARTE LIKE '3%' OR
      NUM_HABITACION LIKE '4%' AND NUM_PARTE LIKE '4%')
);
CREATE TABLE RESERVAS_H(
ID_RESERVA      VARCHAR2(4)   CONSTRAINT R_ID_RES PRIMARY KEY,
NUM_HABITACION  VARCHAR2(2)   CONSTRAINT R_NUM_HAB REFERENCES HABITACIONES_H,
DNI             VARCHAR2(9)   CONSTRAINT R_DNI REFERENCES CLIENTES_H,
FECHA_ENTRADA   DATE          NOT NULL,
DIAS_ESTANCIA   NUMBER(2)
); */

-------------------------------------------------------------------------------

/* INSERT INTO HABITACIONES_H VALUES('19','TRIPLE',1);
INSERT INTO HABITACIONES_H VALUES('25','TRIPLE',2);
INSERT INTO HABITACIONES_H VALUES('30','DOBLE',3);
INSERT INTO HABITACIONES_H VALUES('49','INDIVIDUAL',4);

INSERT INTO CLIENTES_H VALUES('55555555C','Rafael Mart�nez Sobera','876950493');
INSERT INTO CLIENTES_H VALUES('33333333T','Anabel P�rez Ram�rez','665743452');
INSERT INTO CLIENTES_H VALUES('66666666S','Juan Com�n Valero','618304522');
INSERT INTO CLIENTES_H VALUES('99999999N','Sara S�nchez Espinosa','998543212');

INSERT INTO QUEJAS_H VALUES('1111','55555555C', NULL, '23/02/2022');
INSERT INTO QUEJAS_H VALUES('2222','33333333T', 'Problemas con la reserva', '12/01/2022');
INSERT INTO QUEJAS_H VALUES('0333','33333333T', 'Goteras', '03/03/2022');
INSERT INTO QUEJAS_H VALUES('4444','66666666S', NULL, '03/03/2022');

INSERT INTO PARTE_AVERIA_H VALUES('1111','19','Salida de agua en el ba�o','21/02/2022',134.99);
INSERT INTO PARTE_AVERIA_H VALUES('2222','25','Goteras','03/01/2022',84.99);
INSERT INTO PARTE_AVERIA_H VALUES('3333','30','Camas da�adas','19/01/2022',57.99);
INSERT INTO PARTE_AVERIA_H VALUES('4444','49','Aire acondicionado defectuoso','19/02/2022',39.99);

INSERT INTO RESERVAS_H VALUES('1111','19','55555555C','25/02/2022',3);
INSERT INTO RESERVAS_H VALUES('2222','25','33333333T','3/1/22',5);
INSERT INTO RESERVAS_H VALUES('3333','30','66666666S','30/1/22',1);
INSERT INTO RESERVAS_H VALUES('4444','49','99999999N','7/2/22',6); */

-------------------------------------------------------------------------------

--Cambio de tama�o de un campo--
/* ALTER TABLE HABITACIONES_H MODIFY NUM_HABITACION VARCHAR2(2); */

--A�adir un campo de tipo NOT NULL--
/* ALTER TABLE CLIENTES_H ADD PROVINCIA VARCHAR2(20) CONSTRAINT C_PROVIN 
                                                  CHECK(PROVINCIA=UPPER(PROVINCIA));
UPDATE CLIENTES_H SET PROVINCIA='NO ESPECIFICADO';
ALTER TABLE CLIENTES_H MODIFY PROVINCIA NOT NULL; */

--A�adir una restricci�n nueva de tipo CHECK--
/* ALTER TABLE RESERVAS_H MODIFY DIAS_ESTANCIA CONSTRAINT R_DIAS_EST 
                                            CHECK(DIAS_ESTANCIA > 0); */

-------------------------------------------------------------------------------

--Obt�n todos los datos de las reservas realizadas ampliando la informaci�n con
--el nombre y el tel�fono del cliente as� como la planta y el tipo de habitaci�n
--de la habitaci�n reservada ordenados por fecha de entrada.

/* SELECT CL.DNI, NOMBRE, TELEFONO, PLANTA, R.NUM_HABITACION, TIPO, FECHA_ENTRADA, 
       FECHA_ENTRADA+DIAS_ESTANCIA "FECHA_SALIDA"
FROM CLIENTES_H CL JOIN RESERVAS_H R ON CL.DNI=R.DNI
JOIN HABITACIONES_H H ON H.NUM_HABITACION=R.NUM_HABITACION
ORDER BY FECHA_ENTRADA; */

--Obt�n el DNI, el nombre del cliente, la habitaci�n que reserv� junto con el
--desperfecto y la aver�a asociada a la misma (si las tiene) ordenados por
--orden alfab�tico.

/* SELECT R.DNI, NOMBRE, R.NUM_HABITACION, DESPERFECTO "AVERIA", MOTIVO "QUEJA"
FROM PARTE_AVERIA_H P JOIN RESERVAS_H R ON P.NUM_HABITACION=R.NUM_HABITACION
JOIN QUEJAS_H Q ON R.DNI=Q.DNI
JOIN CLIENTES_H CL ON CL.DNI=R.DNI
ORDER BY NOMBRE; */